services:
  api1: &api
    image: jeiferson/rinha-de-backend:latest
    hostname: api1
#    depends_on:
#      database:
#        condition: service_healthy
    environment:
      - PORT=8081
      - R2DBC_URL=r2dbc:postgresql://database:5432/rinhabackend
      - DB_USERNAME=rinhabackend
      - DB_PASSWORD=rinhabackend
      - ENABLE_POOL=true
      - INITIAL_POOL_SIZE=5
      - MAX_POOL_SIZE=10
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - PORT=8082
      - R2DBC_URL=r2dbc:postgresql://database:5432/rinhabackend
      - DB_USERNAME=rinhabackend
      - DB_PASSWORD=rinhabackend
      - ENABLE_POOL=true
      - INITIAL_POOL_SIZE=5
      - MAX_POOL_SIZE=10

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  postgres:
    image: postgres:16.1
    hostname: database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhabackend
    #    healthcheck:
    #      test: [ "CMD-SHELL", "pg_isready", "-U", "rinhabackend", "-d", "rinhabackend" ]
    #      interval: 5s
    #      timeout: 5s
    #      retries: 5
#    ports:
#      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '200MB'